### ISSUE TITLE
GraphFrame dependency issue and ambiguous implicit conversions

### ISSUE THREAD

**Issue by EnricoMi** [G-Research/spark-dgraph-connector#129]
@daveaitel mentioned this issue in #128, I have moved this here:

Also, in Scala, I get this:

scala> val vertices: DataFrame = spark.read.dgraph.vertices(target)
vertices: org.apache.spark.sql.DataFrame = [id: bigint, absfile: string ... 21 more fields]

scala> import uk.co.gresearch.spark.dgraph.graphframes._
import uk.co.gresearch.spark.dgraph.graphframes._

scala> val graph: GraphFrame = spark.read.dgraph.graphframes("localhost:9080")
:30: error: not found: type GraphFrame
val graph: GraphFrame = spark.read.dgraph.graphframes("localhost:9080")
^
:30: error: Symbol 'term org.graphframes' is missing from the classpath.
This symbol is required by 'method uk.co.gresearch.spark.dgraph.graphframes.GraphFramesReader.graphframes'.
Make sure that term graphframes is in your classpath and check for conflicting dependencies with -Ylog-classpath.
A full rebuild may help if 'GraphFramesReader.class' was compiled against an incompatible version of org.
val graph: GraphFrame = spark.read.dgraph.graphframes("localhost:9080")
^

scala> import uk.co.gresearch.spark.dgraph.graphx._
import uk.co.gresearch.spark.dgraph.graphx._

scala> val graph = spark.read.dgraph.graphx("localhost:9080")
:33: error: type mismatch;
found : org.apache.spark.sql.DataFrameReader
required: ?{def dgraph: ?}
Note that implicit conversions are not applicable because they are ambiguous:
both method GraphFrameDataFrameReader in package graphframes of type (reader: org.apache.spark.sql.DataFrameReader)uk.co.gresearch.spark.dgraph.graphframes.package.GraphFrameDataFrameReader
and method GraphxDataFrameReader in package graphx of type (reader: org.apache.spark.sql.DataFrameReader)uk.co.gresearch.spark.dgraph.graphx.package.GraphxDataFrameReader
are possible conversion functions from org.apache.spark.sql.DataFrameReader to ?{def dgraph: ?}
val graph = spark.read.dgraph.graphx("localhost:9080")
^

**Comment by EnricoMi** [comment]
This seem to be two separate issues, lets try to fix the first one (`GraphFrame`).

You have to add the graphframes dependency to your project and need to `import org.graphframes.GraphFrame`.

This should resolve the issue `error: not found: type GraphFrame`.

**Comment by EnricoMi** [comment]
Well, the second issue (`Note that implicit conversions are not applicable because they are ambiguous`) might be because you have these two imports in the same Scala context.

Use either, not both:

    import uk.co.gresearch.spark.dgraph.graphframes._
    import uk.co.gresearch.spark.dgraph.graphx._

So open a new scala REPL or notebook and retry the GraphX bit without importing `uk.co.gresearch.spark.dgraph.graphframes._`:

    scala> import uk.co.gresearch.spark.dgraph.graphx._
    scala> val graph = spark.read.dgraph.graphx("localhost:9080")

**Comment by daveaitel** [comment]
Awesome, thanks!

However, this still leads me to the problem of "no data actually in my
graph" :(
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 3.1.2
      /_/

Using Scala version 2.12.10 (OpenJDK 64-Bit Server VM, Java 11.0.11)
Type in expressions to have them evaluated.
Type :help for more information.

scala> import uk.co.gresearch.spark.dgraph.graphx._
import uk.co.gresearch.spark.dgraph.graphx._

scala> val graph = spark.read.dgraph.graphx("localhost:9080")
graph:
org.apache.spark.graphx.Graph[uk.co.gresearch.spark.dgraph.graphx.VertexProperty,uk.co.gresearch.spark.dgraph.graphx.EdgeProperty]
= ***@***.***

scala> graph.numVertices
res0: Long = 0

**Comment by daveaitel** [comment]
Is it possible that the library only returns vertices that have dgraph.type
set? This seems crazy to me, but since my database might be weird in that
way (I didn't set any types in my schema yet, despite having a million
nodes), I wanted to make sure I mentioned it.

-dave

**Comment by EnricoMi** [comment]
See #128 for the no-data issue.
