### ISSUE TITLE
Ask for a GraphFrame release for Spark 2.4 and Scala 2.12

### ISSUE THREAD

**Issue by EnricoMi** [G-Research/spark-dgraph-connector#40]
All GraphFrame releases for 2.4 are build against Scala 2.11. Many dependencies of the connector require Scala 2.12, so we cannot compile it against 2.11. Therefore, we cannot support GraphFrames for Spark 2.4.

If they would provide a 2.12 release for Spark 2.4, then we could support GraphFrames for 2.4 as well. Spark provides both Scala 2.11 and 2.12.

**Comment by stackedsax** [comment]
Hm, is this likely to happen given Spark 3.0's recent release?  It seems like the community is mostly focused on pushing forward.

**Comment by EnricoMi** [comment]
I am sure Spark 2.4 will be around for a while. I'll raise it with them and see what they say.

**Comment by EnricoMi** [comment]
Looks like many users are looking for this: https://github.com/graphframes/graphframes/issues/364

**Comment by EnricoMi** [comment]
They have released Graphframes 0.8.1 for Spark 2.4 and Scala 2.12. Integrated into our 2.4 branch, tests are green. Will go out in next connector release.
